### ISSUE TITLE
Additional Supported types

### ISSUE THREAD

**Issue by TheAngryByrd** [Zaid-Ajaj/Giraffe.QueryReader#1]
## Description

I think it would be beneficial to also support

- [ ] Int64 (for those really hard to reach numbers)
- [ ] Guid (for Id lookups)
- [ ] DateTime (for time based searches)
- [ ] DateTimeOffset (for time based searches)
- [ ] TimeSpan (for time based searches)
- [ ] Uri (for redirects)

Since this list is a bit extensive, would it be beneficial to use SRTP here and accept anything with a TryParse function?  [Example of using SRTP with tryparse](http://fssnip.net/sT/title/One-tryParse-to-rule-them-all)

## Error messages, screenshots

n/a

## Failing test, failing github repo, or reproduction steps

n/a

## Expected Behavior

n/a

## Known workarounds

n/a

## Other information

* Branch or release version: 1.1.0

**Comment by Zaid-Ajaj** [comment]
Hello @TheAngryByrd , thanks for the suggestions, from your list I can add `int64`, `Guid` and `Uri` but exclude the time based parameters because these are culture specific most of the time and it is up to the users to decide/parse themselves (simply read query string parameter as string and parse yourself). 

Do you want to send a PR for this? 🙏 That would be awesome! if not, I will try to add them myself when time permits 

You can use SRTP if you want, although it is not really necessary. A function that returns `Option<'a>` is more appropriate than the one in the examples with a defaul value, because if we can't parse then it is a bad request, I guess something like this (I haven't tested it):
```fs
  let inline tryParse (text: string) : ^a when ^a : (static member TryParse : string * ^a byref -> bool) = 
    match (^a : (static member TryParse: string * ^a byref -> bool) (text)) with
    | true, value -> Some value
    | false, _ -> None
```

**Comment by TheAngryByrd** [comment]
Ah good point on the time specific stuff.  

Yep, I'll get to a PR shortly!

Yeah my suggestion for using SRTP is only based on the fact that there might be other types that could be supported and instead of having a hardcoded list, as long as the type supported a static tryparse method, this would handle it.

**Comment by Zaid-Ajaj** [comment]
Supporting all types with TryParse, although cool, is not necessary as the list of such types is implemented (numbers, guid, uri) and other types can be parsed just as easily from  string

(sorry for closing the issue, my phone’s screen chose to click things around hahah)
